name: Stable Rust Toolchain

on:
  workflow_call:
    inputs:
      targets:
        description: Comma-separated list of target triples to install for this toolchain
        required: false
        type: string
      components:
        description: Comma-separated list of components to be additionally installed
        required: false
        type: string

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@1.88
      with:
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
