name: ShellCheck

on: [push, pull_request]

permissions:
  contents: read

jobs:
  file-list-up-to-date:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt install ripgrep
    - name: debug
      run: |
        set -x
        pwd
        cat build_tools/shellcheck/included.txt
        [ -f build_tools/shellcheck/excluded.txt ] && echo 'excluded file exists'
        ls
        rg --version
        rg check_for_file_updates
        rg --no-require-git --no-ignore-exclude --stop-on-nonmatch --files-with-matches '^#!.*[^i]sh'
    - name: check for updates
      run: |
        build_tools/shellcheck/check_for_file_updates.sh

  check-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt install shellcheck
    - name: shellcheck
      run: |
        build_tools/shellcheck/check.sh
